[2024-07-31T18:52:50.346+0000] {processor.py:161} INFO - Started process (PID=4455) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:52:50.346+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:52:50.347+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:52:50.347+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:52:50.350+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:52:50.349+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 10
    dag = with DAG(
          ^^^^
SyntaxError: invalid syntax
[2024-07-31T18:52:50.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:52:50.371+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.031 seconds
[2024-07-31T18:52:52.947+0000] {processor.py:161} INFO - Started process (PID=4458) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:52:52.947+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:52:52.948+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:52:52.948+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:52:52.951+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:52:52.950+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 11
    dag = with DAG(
          ^^^^
SyntaxError: invalid syntax
[2024-07-31T18:52:52.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:52:52.973+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.032 seconds
[2024-07-31T18:53:35.340+0000] {processor.py:161} INFO - Started process (PID=4504) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:53:35.342+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:53:35.343+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:53:35.342+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:53:35.346+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:53:35.345+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 11
    dag = with DAG(
          ^^^^
SyntaxError: invalid syntax
[2024-07-31T18:53:35.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:53:35.368+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.034 seconds
[2024-07-31T18:53:55.365+0000] {processor.py:161} INFO - Started process (PID=4525) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:53:55.365+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:53:55.366+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:53:55.366+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:53:55.369+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:53:55.368+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 11
    dag = with DAG(
          ^^^^
SyntaxError: invalid syntax
[2024-07-31T18:53:55.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:53:55.390+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.031 seconds
[2024-07-31T18:54:15.840+0000] {processor.py:161} INFO - Started process (PID=4549) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:54:15.842+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:54:15.842+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:54:15.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:54:15.846+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:54:15.845+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 10
    dag = with DAG(
          ^^^^
SyntaxError: invalid syntax
[2024-07-31T18:54:15.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:54:15.867+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.033 seconds
[2024-07-31T18:54:36.365+0000] {processor.py:161} INFO - Started process (PID=4571) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:54:36.366+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:54:36.367+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:54:36.366+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:54:36.370+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:54:36.369+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 11
[2024-07-31T18:54:36.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:54:36.391+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.032 seconds
[2024-07-31T18:55:17.638+0000] {processor.py:161} INFO - Started process (PID=4618) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:55:17.639+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:55:17.640+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:55:17.640+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:55:17.643+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:55:17.642+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 11
[2024-07-31T18:55:17.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:55:17.665+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.033 seconds
[2024-07-31T18:56:00.684+0000] {processor.py:161} INFO - Started process (PID=4664) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:56:00.685+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:56:00.686+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:56:00.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:56:00.691+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:56:00.688+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 16, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T18:56:00.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:56:00.714+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.036 seconds
[2024-07-31T18:56:45.628+0000] {processor.py:161} INFO - Started process (PID=5000) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:56:45.632+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:56:45.633+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:56:45.633+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:56:45.639+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:56:45.636+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 16, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T18:56:45.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:56:45.696+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.075 seconds
[2024-07-31T18:57:09.667+0000] {processor.py:161} INFO - Started process (PID=5048) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:57:09.667+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:57:09.668+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:57:09.668+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:57:09.674+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:57:09.671+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T18:57:09.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:57:09.698+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.037 seconds
[2024-07-31T18:57:54.731+0000] {processor.py:161} INFO - Started process (PID=5095) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:57:54.732+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:57:54.733+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:57:54.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:57:54.738+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:57:54.735+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T18:57:54.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:57:54.762+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.037 seconds
[2024-07-31T18:58:40.719+0000] {processor.py:161} INFO - Started process (PID=5145) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:58:40.721+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:58:40.722+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:58:40.721+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:58:40.727+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:58:40.724+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T18:58:40.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:58:40.751+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.037 seconds
[2024-07-31T18:59:21.926+0000] {processor.py:161} INFO - Started process (PID=5190) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:59:21.928+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T18:59:21.929+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:59:21.928+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:59:21.934+0000] {logging_mixin.py:188} INFO - [2024-07-31T18:59:21.931+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T18:59:21.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T18:59:21.958+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.037 seconds
[2024-07-31T19:00:04.422+0000] {processor.py:161} INFO - Started process (PID=5234) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:00:04.423+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:00:04.424+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:00:04.424+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:00:04.429+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:00:04.426+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T19:00:04.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:00:04.453+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.037 seconds
[2024-07-31T19:00:27.970+0000] {processor.py:161} INFO - Started process (PID=5261) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:00:27.971+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:00:27.971+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:00:27.971+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:00:27.977+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:00:27.974+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T19:00:27.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:00:28.001+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.037 seconds
[2024-07-31T19:01:12.863+0000] {processor.py:161} INFO - Started process (PID=5307) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:01:12.865+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:01:12.866+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:01:12.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:01:12.871+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:01:12.868+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T19:01:12.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:01:12.895+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.038 seconds
[2024-07-31T19:01:57.915+0000] {processor.py:161} INFO - Started process (PID=5353) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:01:57.916+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:01:57.917+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:01:57.917+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:01:57.922+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:01:57.919+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T19:01:57.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:01:57.947+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.038 seconds
[2024-07-31T19:02:43.593+0000] {processor.py:161} INFO - Started process (PID=5400) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:02:43.595+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:02:43.595+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:02:43.595+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:02:43.601+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:02:43.597+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 18, in <module>
    start_date=days_ago(2),
               ^^^^^^^^
NameError: name 'days_ago' is not defined
[2024-07-31T19:02:43.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:02:43.624+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.036 seconds
[2024-07-31T19:03:03.572+0000] {processor.py:161} INFO - Started process (PID=5423) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:03:03.573+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:03:03.573+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:03.573+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:03:03.580+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:03:03.811+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:03.810+0000] {override.py:1858} INFO - Created Permission View: can edit on DAG:weather-app
[2024-07-31T19:03:03.825+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:03.825+0000] {override.py:1858} INFO - Created Permission View: can read on DAG:weather-app
[2024-07-31T19:03:03.837+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:03.837+0000] {override.py:1858} INFO - Created Permission View: can delete on DAG:weather-app
[2024-07-31T19:03:03.838+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:03.838+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:03:03.848+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:03.847+0000] {dag.py:3111} INFO - Creating ORM DAG for weather-app
[2024-07-31T19:03:03.856+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:03.856+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-30 00:00:00+00:00, run_after=2024-07-31 00:00:00+00:00
[2024-07-31T19:03:03.959+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.394 seconds
[2024-07-31T19:03:49.641+0000] {processor.py:161} INFO - Started process (PID=5470) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:03:49.645+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:03:49.646+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:49.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:03:49.652+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:03:49.667+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:49.667+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:03:49.687+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:03:49.687+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-30 00:00:00+00:00, run_after=2024-07-31 00:00:00+00:00
[2024-07-31T19:03:49.914+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.279 seconds
[2024-07-31T19:18:28.030+0000] {processor.py:161} INFO - Started process (PID=5583) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:18:28.032+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:18:28.033+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:18:28.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:18:28.042+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:18:28.054+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:18:28.054+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:18:28.075+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:18:28.075+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:18:28.099+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.075 seconds
[2024-07-31T19:19:33.838+0000] {processor.py:161} INFO - Started process (PID=5650) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:19:33.840+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:19:33.842+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:19:33.841+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:19:33.848+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:19:33.951+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:19:33.950+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:19:33.968+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:19:33.967+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:19:34.093+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.260 seconds
[2024-07-31T19:20:29.791+0000] {processor.py:161} INFO - Started process (PID=5706) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:20:29.792+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:20:29.794+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:20:29.793+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:20:29.800+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:20:29.815+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:20:29.815+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:20:29.835+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:20:29.835+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:20:29.859+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.074 seconds
[2024-07-31T19:20:54.264+0000] {processor.py:161} INFO - Started process (PID=5731) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:20:54.265+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:20:54.267+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:20:54.266+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:20:54.279+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:20:54.273+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 38, in <module>
    transform_data = PythonOperator(
                     ^^^^^^^^^^^^^^
NameError: name 'PythonOperator' is not defined
[2024-07-31T19:20:54.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:20:54.305+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.046 seconds
[2024-07-31T19:21:18.906+0000] {processor.py:161} INFO - Started process (PID=5756) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:21:18.908+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:21:18.909+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:21:18.909+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:21:18.921+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:21:18.915+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 38, in <module>
    transform_data = PythonOperator(
                     ^^^^^^^^^^^^^^
NameError: name 'PythonOperator' is not defined
[2024-07-31T19:21:18.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:21:18.946+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.045 seconds
[2024-07-31T19:21:42.490+0000] {processor.py:161} INFO - Started process (PID=5781) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:21:42.491+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:21:42.493+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:21:42.493+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:21:42.501+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:21:42.496+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 5, in <module>
    from airflow.providers.http.operators.http import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.providers.http.operators.http' (/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/providers/http/operators/http.py)
[2024-07-31T19:21:42.503+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:21:42.527+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.043 seconds
[2024-07-31T19:22:06.589+0000] {processor.py:161} INFO - Started process (PID=5804) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:22:06.590+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:22:06.592+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:22:06.591+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:22:07.049+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:22:07.043+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 42, in <module>
    python_callable=transform_data
                    ^^^^^^^^^^^^^^
NameError: name 'transform_data' is not defined
[2024-07-31T19:22:07.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:22:07.071+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.488 seconds
[2024-07-31T19:22:54.662+0000] {processor.py:161} INFO - Started process (PID=5854) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:22:54.663+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:22:54.665+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:22:54.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:22:55.115+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:22:55.108+0000] {dagbag.py:355} ERROR - Failed to import: /home/ubuntu/airflow/dags/weather_dags.py
Traceback (most recent call last):
  File "/home/ubuntu/airflow-venv/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/weather_dags.py", line 42, in <module>
    python_callable=transform_data
                    ^^^^^^^^^^^^^^
NameError: name 'transform_data' is not defined
[2024-07-31T19:22:55.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:22:55.137+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.481 seconds
[2024-07-31T19:23:36.868+0000] {processor.py:161} INFO - Started process (PID=5899) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:23:36.870+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:23:36.871+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:23:36.870+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:23:37.302+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:23:37.393+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:23:37.392+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:23:37.408+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:23:37.408+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:23:37.436+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.573 seconds
[2024-07-31T19:24:31.279+0000] {processor.py:161} INFO - Started process (PID=5960) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:24:31.280+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:24:31.281+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:24:31.281+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:24:31.730+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:24:31.742+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:24:31.742+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:24:31.761+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:24:31.760+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:24:31.782+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.509 seconds
[2024-07-31T19:24:50.750+0000] {processor.py:161} INFO - Started process (PID=5982) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:24:50.750+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:24:50.751+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:24:50.751+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:24:51.196+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:24:51.208+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:24:51.208+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:24:51.226+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:24:51.226+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:24:51.249+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.505 seconds
[2024-07-31T19:25:38.381+0000] {processor.py:161} INFO - Started process (PID=6034) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:25:38.383+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:25:38.384+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:25:38.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:25:38.843+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:25:38.855+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:25:38.855+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:25:38.872+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:25:38.872+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:25:38.897+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.522 seconds
[2024-07-31T19:26:01.618+0000] {processor.py:161} INFO - Started process (PID=6058) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:26:01.619+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:26:01.620+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:26:01.619+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:26:02.072+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:26:02.083+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:26:02.083+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:26:02.102+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:26:02.102+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:26:02.126+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.514 seconds
[2024-07-31T19:26:54.960+0000] {processor.py:161} INFO - Started process (PID=6115) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:26:54.962+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:26:54.963+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:26:54.963+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:26:55.399+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:26:55.410+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:26:55.410+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:26:55.427+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:26:55.427+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:26:55.448+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.494 seconds
[2024-07-31T19:27:55.006+0000] {processor.py:161} INFO - Started process (PID=6179) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:27:55.008+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:27:55.009+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:27:55.008+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:27:55.448+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:27:55.461+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:27:55.460+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:27:55.478+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:27:55.477+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:27:55.500+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.499 seconds
[2024-07-31T19:28:47.753+0000] {processor.py:161} INFO - Started process (PID=6233) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:28:47.755+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:28:47.755+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:28:47.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:28:48.188+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:28:48.199+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:28:48.199+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:28:48.218+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:28:48.217+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:28:48.247+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.500 seconds
[2024-07-31T19:29:33.540+0000] {processor.py:161} INFO - Started process (PID=6282) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:29:33.541+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:29:33.542+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:29:33.541+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:29:33.987+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:29:33.998+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:29:33.998+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:29:34.015+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:29:34.015+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:29:34.039+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.505 seconds
[2024-07-31T19:30:16.970+0000] {processor.py:161} INFO - Started process (PID=6333) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:30:16.972+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:30:16.972+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:30:16.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:30:17.413+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:30:17.426+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:30:17.425+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:30:17.443+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:30:17.443+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:30:17.467+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.502 seconds
[2024-07-31T19:31:05.293+0000] {processor.py:161} INFO - Started process (PID=6382) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:31:05.295+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:31:05.296+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:31:05.295+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:31:05.730+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:31:05.741+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:31:05.740+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:31:05.758+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:31:05.758+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:31:05.779+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.492 seconds
[2024-07-31T19:31:27.160+0000] {processor.py:161} INFO - Started process (PID=6406) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:31:27.161+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:31:27.161+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:31:27.161+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:31:27.589+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:31:27.680+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:31:27.680+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:31:27.695+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:31:27.695+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:31:27.720+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.566 seconds
[2024-07-31T19:32:37.351+0000] {processor.py:161} INFO - Started process (PID=6483) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:32:37.354+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:32:37.355+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:32:37.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:32:37.804+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:32:37.815+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:32:37.815+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:32:37.834+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:32:37.833+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:32:37.855+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.510 seconds
[2024-07-31T19:33:45.635+0000] {processor.py:161} INFO - Started process (PID=6556) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:33:45.637+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:33:45.638+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:33:45.638+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:33:46.086+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:33:46.098+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:33:46.097+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:33:46.114+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:33:46.114+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:33:46.138+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.508 seconds
[2024-07-31T19:34:18.309+0000] {processor.py:161} INFO - Started process (PID=6590) to work on /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:34:18.311+0000] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/weather_dags.py for tasks to queue
[2024-07-31T19:34:18.312+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:34:18.311+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:34:18.778+0000] {processor.py:840} INFO - DAG(s) 'weather-app' retrieved from /home/ubuntu/airflow/dags/weather_dags.py
[2024-07-31T19:34:18.790+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:34:18.789+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-07-31T19:34:18.808+0000] {logging_mixin.py:188} INFO - [2024-07-31T19:34:18.808+0000] {dag.py:3947} INFO - Setting next_dagrun for weather-app to 2024-07-31 00:00:00+00:00, run_after=2024-08-01 00:00:00+00:00
[2024-07-31T19:34:18.832+0000] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/weather_dags.py took 0.528 seconds
